#Version 1 de Dockerfile
FROM    elasticsearch:5.5 
LABEL   description="This is a custom elasticsearch container image" \
        author="Hector Martinez <hmartinez.py@gmail.com>"

EXPOSE 9200 
EXPOSE 9300 
